flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField, TextAreaField,SelectMultipleField
from wtforms.validators import DataRequired



class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    tags = SelectMultipleField('Tag',validators=[DataRequired()],coerce=int)
    submit = SubmitField('Create')

flaskblog/posts/routes.py
from flask import  render_template, url_for,flash, redirect, request, abort,Blueprint
from flaskblog.posts.forms import PostForm
from flaskblog.models import Post,Tag
from flaskblog import db
from flask_login import current_user, login_required
from pprint import pprint


posts = Blueprint('posts', __name__)


@posts.route('/post')
@login_required
def index_post():
    page = request.args.get('page',1,type=int)
    posts =Post.query.order_by(Post.date_posted.desc()).paginate(per_page=5,page = page)
    return render_template('posts/index.html', posts=posts)

@posts.route('/user/<string:username>')
@login_required
def user_posts(username):
    page = request.args.get('page',1,type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts =Post.query.filter_by(author=user)\
            .order_by(Post.date_posted.desc())\
            .paginate(per_page=5,page = page)
    return render_template('posts/user_posts.html', posts=posts,user=user)

@posts.route('/post/new', methods=['GET','POST'])
@login_required
def new_post():
    form = PostForm()
    form.tags.choices = [(t.id, t.name) for t in Tag.query.order_by('name')]
    if form.validate_on_submit():
        #pprint(form.tags.data)
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        for id in form.tags.data:
            post.tags.append(Tag.query.get(id))
        db.session.add(post)
        db.session.commit()
        flash('Post created successfully', 'success')
        return redirect( url_for('posts.index_post'))
    return render_template('posts/create.html', form=form)

@posts.route('/post/<int:post_id>')
@login_required
def post(post_id):
    post =Post.query.get_or_404(post_id)
    return render_template('posts/detail.html', post=post)

@posts.route('/post/<int:post_id>/update', methods=['GET','POST'])
@login_required
def update_post(post_id):
    post =Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    form.tags.choices = [(t.id, t.name) for t in Tag.query.order_by('name')]
    if form.validate_on_submit():
        post.title= form.title.data 
        post.content=form.content.data
        
        for ptag in post.tags:
            post.tags.remove(ptag)

        for id in form.tags.data:
            tag = Tag.query.get(id)
            post.tags.append(tag)
                   
        db.session.commit()
        flash('Post Update successfully', 'success')
        return redirect( url_for('posts.post',post_id = post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
        form.tags.data = [(tag.id)for tag in post.tags]
    return render_template('posts/update.html', form =form)


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post =Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Post deleted successfully', 'success')
    return redirect( url_for('posts.index_post'))

flaskblog/users/routes.py
from flask import  render_template, url_for,flash, redirect, request, abort,Blueprint
from flaskblog.users.forms import RegistrationForm, LoginForm, UpddateAccountForm, RequestResetForm,ResetPasswordForm,ChangePasswordForm
from flaskblog.models import User,Post
from flaskblog import db, bcrypt, mail
from flask_login import login_user, current_user, logout_user, login_required
import json
from flaskblog.users.utils import save_picture, send_reset_email



users = Blueprint('users', __name__)


@users.route('/register', methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('posts.index_post'))
    form = RegistrationForm();
    if form.validate_on_submit():
        hash_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(
            username = form.username.data,
            email = form.email.data,
            password = hash_pw
        )
        db.session.add(user)
        db.session.commit()
        flash('Account created succesfully, Please Login', 'success')
        return redirect(url_for('users.login'))
    return render_template('accounts/register.html', form=form)

@users.route('/login', methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('posts.index_post'))
    form =LoginForm();
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('posts.index_post'))
        else:
            flash('Email or password is incorrect', 'danger')
    return render_template('accounts/login.html', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route('/account', methods=['GET','POST'])
@login_required
def account():
    form = UpddateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Account updated successfully', 'success')
        return redirect( url_for('users.account'))
        #image_file = url_for('static',filename = 'profile_pics/'+current_user.image_file)
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template('accounts/profile.html', form = form)



@users.route('/user/<string:username>')
@login_required
def user_posts(username):
    page = request.args.get('page',1,type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts =Post.query.filter_by(author=user)\
            .order_by(Post.date_posted.desc())\
            .paginate(per_page=5,page = page)
    return render_template('posts/user_posts.html', posts=posts,user=user)





@users.route('/reset_password', methods=['GET','POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('posts.index_post'))

    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has sent to your email with instructions', 'info')
        return redirect(url_for('users.login'))
    return render_template('accounts/reset_request.html', form =form)


@users.route('/reset_password/<token>', methods=['GET','POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('posts.index_post'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token','warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hash_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hash_pw
        db.session.commit()
        flash('Password change succesfully, Please Login', 'success')
        return redirect(url_for('users.login'))
    return render_template('accounts/reset_token.html', form =form) 

@users.route('/change_password', methods=['GET', 'POST'])
@login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        hash_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        current_user.password = hash_pw
        db.session.commit()
        flash('Password change succesfully, Please Login', 'success')
        return redirect(url_for('users.change_password'))
    return render_template('accounts/change_password.html', form =form) 

flaskblog/templates/posts/create.html
{% extends 'layouts/app.html' %}

{% block content %}
<div class="row my-3" >
    <div class="col-3">
       {% include 'posts/partials/sidebar.html' %}
    </div>
    <div class="col-8 offset-1  card py-3" style="min-height: 100vh;">

        <form method="post" novalidate class="">
            <fieldset><legend>Create Post</legend>
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                        {{ form.title(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.content.label(class="form-control-label") }}
                    {% if form.content.errors %}
                        {{ form.content(class="form-control is-invalid",rows="10") }}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.content(class="form-control",rows="10") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.tags.label(class="form-control-label") }}
                    {% if form.tags.errors %}
                        {{ form.tags(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.tags.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.tags(class="form-control") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>


    </div>
</div>

{% endblock %}

flaskblog/templates/posts/detail.html
{% extends 'layouts/app.html' %}

{% block content %}
<div class="row my-3">
    <div class="col-3">
       {% include 'posts/partials/sidebar.html' %}
    </div>
    <div class="col-8 offset-1  card py-3" style="min-height: 100vh;">
      {% include 'shared/flash_msg.html' %}
        <div class="media">
            <a class="pull-left" href="#">
              <img style="max-width: 150px;" class="media-object" src="{{ url_for('static',filename = 'profile_pics/'+post.author.image_file) }}">
            </a>
            <div class="media-body p-2">
                <div class="row">
                  <div class="col-8">
                    <h4 class="media-heading">{{ post.title }}</h4>
                    <p class="text-right">By {{ post.author.username }} on {{ post.date_posted.strftime('%Y-%m-%d') }}</p>
                  </div>
                  <div class="col-4">
                    {% if post.author == current_user %}
                      <a class="btn btn-sm btn-outline-info" href="{{ url_for('posts.update_post',post_id= post.id) }}">Edit</a>
                      <a class="btn btn-sm btn-outline-danger" data-toggle="modal" data-target="#exampleModal" href="#">Delete</a>
                    {% endif %}

                  </div>
                </div>
                

                <p>{{ post.content }}</p>
            
            </div>
        </div>


    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <form action="{{ url_for('posts.delete_post', post_id = post.id) }}" method="POST">
          <button type="submit" class="btn btn-danger">Delete</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

flaskblog/templates/posts/index.html
{% extends 'layouts/app.html' %}

{% block content %}
<div class="row my-3">
    <div class="col-3">
       {% include 'posts/partials/sidebar.html' %}
    </div>
    <div class="col-8 offset-1  card py-3">
      {% include 'shared/flash_msg.html' %}
        {% for post in posts.items %}
        <div class="media">
            <a class="pull-left" href="#">
              <img style="max-width: 100px;" class="media-object rounded" src="{{ url_for('static',filename = 'profile_pics/'+post.author.image_file) }}">
            </a>
            <div class="media-body p-2">
                <div class="row">
                  <div class="col-4">
                    <h4 class="media-heading"><a href="{{ url_for('posts.post',post_id = post.id) }}">{{ post.title }}</a></h4>
                  </div>
                  <div class="col-8">
                    <p class="text-right">By <a href="{{ url_for('users.user_posts',username = post.author.username) }}">{{ post.author.username }}</a> on {{ post.date_posted.strftime('%Y-%m-%d') }}</p>
                  </div>
                  <div class="col-12">
                    {% for tag in post.tags %}
                        <span class="badge badge-secondary">{{ tag.name }}</span>
                    {% endfor %}
                  </div>
                </div>
                

                <p>{{ post.content[:200] }}</p>
            
            </div>
        </div>
        <hr />
        {% endfor %}
        <ul class="pagination justify-content-center" style="margin:20px 0">
        {% for page_num in posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
          {% if page_num %}
            {% if posts.page == page_num %}
              <li class="page-item active"><a class="page-link" href="{{ url_for('posts.index_post',page=page_num) }}">{{ page_num }}</a></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="{{ url_for('posts.index_post',page=page_num) }}">{{ page_num }}</a></li>
            {% endif %}
           
          {% else %}
            ...
          {% endif %}
        {% endfor %}
            </ul>

    </div>
</div>

{% endblock %}

flaskblog/templates/posts/update.html
{% extends 'layouts/app.html' %}

{% block content %}
<div class="row my-3" >
    <div class="col-3">
       {% include 'posts/partials/sidebar.html' %}
    </div>
    <div class="col-8 offset-1  card py-3" style="min-height: 100vh;">

        <form method="post" novalidate class="">
            <fieldset><legend>Update Post</legend>
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                        {{ form.title(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.content.label(class="form-control-label") }}
                    {% if form.content.errors %}
                        {{ form.content(class="form-control is-invalid",rows="15") }}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.content(class="form-control",rows="15") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.tags.label(class="form-control-label") }}
                    {% if form.tags.errors %}
                        {{ form.tags(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.tags.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.tags(class="form-control") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>


    </div>
</div>

{% endblock %}

flaskblog/templates/posts/user_posts.html
{% extends 'layouts/app.html' %}

{% block content %}
<div class="row my-3">
    <div class="col-3">
       {% include 'posts/partials/sidebar.html' %}
    </div>
    <div class="col-8 offset-1  card py-3">
        <h2>Posts by {{ user.username }} ( {{ posts.total }} )</h2>
        {% include 'shared/flash_msg.html' %}
        {% for post in posts.items %}
        <div class="media">
            <a class="pull-left" href="#">
              <img style="max-width: 300px;" class="media-object rounded" src="{{ url_for('static',filename = 'profile_pics/'+post.author.image_file) }}">
            </a>
            <div class="media-body p-2">
                <div class="row">
                  <div class="col-4">
                    <h4 class="media-heading"><a href="{{ url_for('posts.post',post_id = post.id) }}">{{ post.title }}</a></h4>
                  </div>
                  <div class="col-8">
                    <p class="text-right">By <a href="#">{{ post.author.username }}</a> on {{ post.date_posted.strftime('%Y-%m-%d') }}</p>
                  </div>
                </div>
                

                <p>{{ post.content[:200] }}</p>
            
            </div>
        </div>
        <hr />
        {% endfor %}
        <ul class="pagination justify-content-center" style="margin:20px 0">
        {% for page_num in posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
          {% if page_num %}
            {% if posts.page == page_num %}
              <li class="page-item active"><a class="page-link" href="{{ url_for('posts.user_posts', username=user.username , page=page_num) }}">{{ page_num }}</a></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="{{ url_for('posts.user_posts', username=user.username,page=page_num) }}">{{ page_num }}</a></li>
            {% endif %}
           
          {% else %}
            ...
          {% endif %}
        {% endfor %}
            </ul>
    </div>
</div>

{% endblock %}